### ISSUE TITLE
seiso-import-master expects a singleton JSON object and can't cope with a list

### ISSUE THREAD

**Issue by wilkotom** [ExpediaDotCom/seiso-import_master#28]
I want to keep nodes in related service instances in the same JSON file. The default syntax for a node file is as follows:

      {
           "type": "nodes",
           "serviceInstance": "example-service-instance-1",
           "items": [
               {
                 "name": "srvexample001-example",
                 "machine": "srvexample001.example.com",
               }
     }

However I have two closely related service instances which will in the future be conflated into a single instance. I have to create separate files for each of these, whereas what I'd like to do is supply them as a list in a JSON file, like this:

    [
        {
             "type": "nodes",
             "serviceInstance": "example-service-instance-1",
             "items": [
                 {
                   "name": "srvexample001-example",
                   "machine": "srvexample001.example.com",
                 }
       },
        {
             "type": "nodes",
             "serviceInstance": "example-service-instance-2",
             "items": [
                 {
                   "name": "srvexample002-example",
                   "machine": "srvexample002.example.com",
                 }
       }
    ]

The importer should be able to detect whether or not it has been supplied with a list of objects or a singleton, and in the former case, iterate over each supplied object in turn.

The error message supplied when attempting to import a list in this case is:

    LONC02ML1VLFD58:prod twilkinson$ seiso-import-master nodes-example-prod.json 
    Using: /Users/twilkinson/.seiso-importers/seiso-prod.yml
    Using: format=json
    Using SSL
    Processing: nodes-example-prod.json
    /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/lib/seiso/import_master.rb:78:in `[]': can't convert String into Integer (TypeError)
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/lib/seiso/import_master.rb:78:in `import_file'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/lib/seiso/import_master.rb:68:in `block in import_files'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/lib/seiso/import_master.rb:65:in `loop'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/lib/seiso/import_master.rb:65:in `import_files'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/gems/seiso-import_master-0.0.12/bin/seiso-import-master:51:in `<top (required)>'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/bin/seiso-import-master:23:in `load'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/bin/seiso-import-master:23:in `<main>'
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'    
    	from /Users/twilkinson/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'

**Comment by williewheeler** [comment]
In principle there's nothing to prevent us from doing this, but to me it seems like there's value in having a single consistent approach to the schema across all entity types and across all files. It just makes things simpler for users.

In your example, what's to prevent somebody from putting two different types of entity in the list? (E.g. mixing services and service instances in a single file.) Is allowing that part of the proposal? I can see that making it tricky to find things, where now it's pretty easy.

If that's not the proposal, then why repeat "type": "nodes" instead of just declaring the type once at the top, and then having a list like this...

    {
      "type": "nodes",
      "serviceInstanceNodes": [ {
        "serviceInstance": "example-service-instance-1",
        "items": [ ... ]
      }, {
        "serviceInstance": "example-service-instance-2",
        "items": [ ... ]
      } ]
    }

It starts getting complicated. That's why I'd prefer to keep the schema pretty basic.

Couldn't you just use related filenames in this sort of situation; e.g., service-instances-example-1.json and service-instances-example-2.json?
