### ISSUE TITLE
Importer should provide meaningful error message when data master doesn't contain type

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso-import_master#5]
Currently it just says

    /Users/wwheeler/.rvm/gems/ruby-1.9.3-p551/gems/seiso-import_master-0.0.5/lib/seiso/import_master.rb:58:in `[]': can't convert String into Integer (TypeError)
        from /Users/wwheeler/.rvm/gems/ruby-1.9.3-p551/gems/seiso-import_master-0.0.5/lib/seiso/import_master.rb:58:in `import_doc'
        from /Users/wwheeler/.rvm/gems/ruby-1.9.3-p551/gems/seiso-import_master-0.0.5/lib/seiso/import_master.rb:53:in `import_file'

**Comment by williewheeler** [comment]
Would be nice to implement this as a general schema validator.

**Comment by williewheeler** [comment]
Done
